version: "3.2"

services:
  api:
    image: pai-api
    build: ./
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env.docker
    depends_on:
      - db
    volumes:
      - ./files:/app/files

  db:
    image: mysql:8.0
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
